#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <vector>

namespace vc {

// Index into BlockRegistry. 0 is always air. uint16_t leaves room for far
// more block types than we'll need before palette compression lands.
using BlockId = uint16_t;

// Order matters: used to index BlockDef::faceTiles and the mesher's tables.
enum class BlockFace : uint8_t { PosX = 0, NegX, PosY, NegY, PosZ, NegZ };

struct BlockDef {
    std::string name;
    bool opaque = true;   // hides adjacent faces
    bool solid = true;    // collision (used from M6)
    bool cutout = false;  // non-opaque cube meshed normally; texture alpha holes
                          // are alpha-tested away in chunk.frag (leaves)
    bool cross = false;   // plant: two diagonal alpha-tested quad pairs instead of
                          // a cube; targetable by raycast but never collides
    bool replaceable = false; // liquids flow into it and falling blocks crush it
                              // (tall grass, flowers — destroyed, not blocking)
    bool liquid = false;  // meshed into the blended pass; liquid-liquid faces cull
    bool gravity = false; // falls when unsupported (block-update ticks)
    bool unbreakable = false; // the break edit refuses it (bedrock; no
                              // hardness system, so a simple guard)
    // Skylight attenuation for non-opaque blocks, 0..15: blocks direct
    // (straight-down) sky and costs max(1, lightOpacity) per propagation
    // step. Ignored when opaque (opaque always blocks fully). Leaves 1,
    // water 3 — vanilla's values.
    uint8_t lightOpacity = 0;
    // Liquids only: 8 = source, 7..1 = flow strength (decays away from the
    // source; 0 on everything else). Drives the spread/recede block updates.
    uint8_t liquidLevel = 0;
    uint8_t emission = 0; // block light emitted, 0..15
    // Vanilla hardness: bare-hand break time is hardness * 1.5 seconds
    // (digSpeed 1 / hardness / 30 damage per tick at 20 TPS). 0 breaks
    // instantly (plants). Unbreakable blocks use the flag, not -1.
    float hardness = 1.0f;
    // What breaking one of these yields: kDropSelf (default), Air for
    // nothing (leaves, tall grass), or a specific id (stone -> cobble).
    static constexpr BlockId kDropSelf = 0xFFFF;
    BlockId drop = kDropSelf;
    std::array<uint16_t, 6> faceTiles{}; // texture-array layer per face

    BlockId ResolveDrop(BlockId self) const { return drop == kDropSelf ? self : drop; }

    static BlockDef Uniform(std::string name, uint16_t tile) {
        BlockDef def;
        def.name = std::move(name);
        def.faceTiles.fill(tile);
        return def;
    }
};

class BlockRegistry {
public:
    static BlockRegistry& Get();

    BlockId Register(BlockDef def);
    const BlockDef& Def(BlockId id) const { return m_defs[id]; }
    // Registration-time patching only (cross-referencing drops whose target
    // id is registered later, e.g. stone -> cobblestone).
    BlockDef& EditDef(BlockId id) { return m_defs[id]; }
    size_t Count() const { return m_defs.size(); }

private:
    BlockRegistry(); // registers air as id 0
    std::vector<BlockDef> m_defs;
};

// Well-known block ids, assigned by RegisterDefaults() at startup.
namespace blocks {

inline constexpr BlockId Air = 0;
extern BlockId Stone;
extern BlockId Dirt;
extern BlockId Grass;
extern BlockId Glowstone;
extern BlockId Sand;
extern BlockId Log;
extern BlockId Leaves;
extern BlockId Water; // source block (liquidLevel 8); world gen places only this
// Flowing water by strength: WaterFlows[level - 1] for levels 1..7.
extern std::array<BlockId, 7> WaterFlows;
extern BlockId SnowyGrass; // M15 snowy-biome surface (snow top, snowed sides)
// M16 cross-mesh plants: need earth (grass/dirt) underfoot...
extern BlockId TallGrass;
extern BlockId Dandelion;
extern BlockId Poppy;
extern BlockId DeadBush; // ...except the dead bush, which needs sand
// M16 tree species (birch in forests, spruce in snow) + the desert cactus
// (full cube for now; vanilla's 14/16 inset is a later polish).
extern BlockId BirchLog;
extern BlockId BirchLeaves;
extern BlockId SpruceLog;
extern BlockId SpruceLeaves;
extern BlockId Cactus; // needs sand (or more cactus) underfoot
// M16: vanilla's buffer under sandy surfaces — carvable but never falls,
// so caves under deserts/beaches mostly expose sandstone ceilings instead
// of floating sand (Biome.generateBiomeTerrain's sand->sandstone rule).
extern BlockId Sandstone;
extern BlockId Bedrock; // unbreakable world floor (solid y0, ragged y1-4)
// M18: what stone drops when mined (never generated by terrain).
extern BlockId Cobblestone;

// M18 crack overlay: destroy_stage_0..9 occupy ten consecutive texture
// layers right after the block tiles — keep BOTH scripts/gen_textures.py
// and scripts/import_mc_assets.py in sync with this.
inline constexpr uint16_t kFirstCrackTile = 29;

void RegisterDefaults();

} // namespace blocks

} // namespace vc
